### ISSUE TITLE
 I get error: got Future <Future pending> attached to a different loop

### ISSUE THREAD

**Issue by sviatoslavadamiv** [awolverp/pyrostep#1]
I am using pyrogram and pyrostep to handle answers of users. I have this function to take feedback from users:

`bot = Client("my_bot", api_id=api_id, api_hash=api_hash, bot_token=BOT_TOKEN, in_memory=True)
pyrostep.listen(bot)

@bot.on_message(filters.command(["feedback"]))
async def send_feedback(client, message) -> None:
    interface_lang = user.User.get_user(message).interface_lang
    feedback_text = translation.get_translation(interface_lang, 'feedback_message')

    await bot.send_message(
        chat_id=message.chat.id,
        text=feedback_text,
        reply_markup=back_keyboard
    )

    message = await pyrostep.wait_for(message.from_user.id)

    await bot.send_message(
        DEVELOPER_ID,
        text=f'Feedback: {message.text}\n\n'
             f'From: @{message.from_user.username}\n\n'
             f'Time: {datetime.datetime.now(central_europe_timezone)}',
    )
    
    await bot.send_message(
        chat_id=message.chat.id,
        text=translation.get_translation(interface_lang, 'thank_you_feedback'),
        reply_markup=get_main_keyboard(interface_lang)
    )`
    
And when this code gets to the point of waiting for a user response, I get this error:

Task <Task pending name='Task-56' coro=<Dispatcher.handler_worker() running at /Users/sviat/Documents/own_projects/telebot_converter/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py:240>> got Future <Future pending> attached to a different loop
Traceback (most recent call last):
  File "/Users/sviat/Documents/own_projects/telebot_converter/venv/lib/python3.10/site-packages/pyrogram/dispatcher.py", line 240, in handler_worker
    await handler.callback(self.client, *args)
  File "/Users/sviat/Documents/own_projects/telebot_converter/tbot.py", line 252, in send_feedback
    message = await pyrostep.wait_for(message.from_user.id)
  File "/Users/sviat/Documents/own_projects/telebot_converter/venv/lib/python3.10/site-packages/pyrostep/steps.py", line 175, in wait_for
    return await _wait_future(id, timeout, store or root)
  File "/Users/sviat/Documents/own_projects/telebot_converter/venv/lib/python3.10/site-packages/pyrostep/steps.py", line 147, in _wait_future
    return await asyncio.wait_for(fn, timeout)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/tasks.py", line 408, in wait_for
    return await fut
    
 What could be the problem and how to solve it ?

**Comment by awolverp** [comment]
@sviatoslavadamiv 
What is your python version?
This code has no error! Did you use any different loop in your code?

**Comment by sviatoslavadamiv** [comment]
I find out that uvloop library give this error with pyrostep. I use it to speedup my code as it said in pyrogram documentation 
https://docs.pyrogram.org/topics/speedups

**Comment by awolverp** [comment]
I'll check it, if there is a problem from pyrostep, i'll fix it ...
