### ISSUE TITLE
force type

### ISSUE THREAD

**Issue by fx505** [awolverp/pyrostep#2]
Is it possible to force typing or use pyrogram filters?
For example, the user can only send photos

**Comment by awolverp** [comment]
No there's no way to set filters.
I can't promise that I will add it.
Pyrogram is gonna be deprecated

**Comment by fx505** [comment]
Do you suggest an alternative to Pyrogram?

**Comment by awolverp** [comment]
Use [Telethon](https://github.com/LonamiWebs/Telethon) instead of Pyrogram.
Or its forks, such as [This](https://github.com/KurimuzonAkuma/pyrogram) or [Pyrofork](https://github.com/Mayuri-Chan/pyrofork); I don't know which fork is better
I using Telethon.

**Comment by fx505** [comment]
thanks
